import 'package:flutter/material.dart';
const baseurl = "https://www.cowdiar.com/"; // https://www.example.com
const version = "api/v1";
const url ="/home";
const register ="/register-user";
const loginurl ="/login-user";
const categorylink = "/categories";
const subcatlink = "/sub-categories/";
const forgetpasslink = "/forgot-password";
const searchurl = "/s";
const sitedetails = "/app-info";
const profile='/my-profile';
const manage="/manage-orders";
const sellingorder="/selling-orders";
const orderdetails="/order-details";
const sendmsg="/send-message";
const notificationlink ="/notifications";
const manrequestlink = "/manage-requests";
const statuscheck = "/get-online-status";
const inboxbox="/inbox";
const inboxdetails='/single-message';
const inboxsend='/send-new-message';
const viewofferlink ='/view-offers';
const requestlink ='/request-action';
const actionlink ='/single-message-action';
const notificationactionlink ='/notification-action';
const sendfeedback ='/send-feedback';
const contactuspage ='/contact-me';
const cartpagelink ='/cart';
const addcartpage ='/add-to-cart';
const removecart ='/remove-from-cart';
const changecart ='/change-quantity';
const coupon= '/apply-coupon';
const updateonlinestatus= '/update-online-status';
const postrequest= '/post-request';
const privacypolicy='/page/privacy-policy';
const termslink='/terms_and_conditions';
const getenquirytypes='/get-enquiry-types';
const getnotifaction='/seller-push-notification-setting';
const postnotifaction='/push-notification-setting';
const deliverapidate='/delivery-times';
const primarycolor = Colors.blue;
const secondercolor = Colors.black54;
// login and reginer screen wave color
final wavefirst = Colors.red[100];
final wavesecond = Colors.red[200];

// all over application icon color overlay
const iconcolor = Colors.red;